# Generated by Django 3.2.4 on 2021-07-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=50)),
                ('startdatetime', models.DateTimeField()),
                ('event_head', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Uploads')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory')),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.departments')),
            ],
        ),
    ]
