# Generated by Django 3.2.4 on 2021-07-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
