# Generated by Django 3.2.4 on 2021-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='regtime',
            field=models.DateTimeField(null=True),
        ),
    ]
