# Generated by Django 3.2.4 on 2021-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('f_email', models.EmailField(max_length=50)),
                ('feedback', models.CharField(max_length=400)),
            ],
        ),
    ]
