# Generated by Django 3.2.4 on 2021-07-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210727_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
