# Generated by Django 3.2.4 on 2021-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedname', models.CharField(max_length=20)),
                ('feedemail', models.EmailField(max_length=20)),
                ('feedmsg', models.CharField(max_length=100)),
            ],
        ),
    ]
