# Generated by Django 3.2.4 on 2021-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedemail',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedmsg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
