# Generated by Django 3.2.4 on 2021-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210728_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedemail',
            field=models.EmailField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedmsg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
