# Generated by Django 3.2.4 on 2021-07-31 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
